### PR TITLE
Use strlen(buffer) to determine break and append size

### LINKED ISSUE #174: Text is truncated due to multiple trailing zeros in buffer
## Environment

* nanodbc version: 
* DBMS name/version: SQLServer
* ODBC connection string: 
* OS and Compiler: Ubuntu g++
* CMake settings: 

## Actual behavior

This issue is from https://github.com/r-dbi/odbc/issues/171. When I query a specific row of my table, the text field yields `buffer` with multiple trailing zeros that is appended to `std::string out`, making `out` terminated early too. It's a database managed by third-party data provider, I have no control over it. I'm not sure how this can happen but it actually does.

https://github.com/nanodbc/nanodbc/blob/0f230abfc08e1a6ebe2a5319ebd93129202bb131/nanodbc/nanodbc.cpp#L2927-L2934

I print the hex code of each buffer (with buffer size = 256), it seems that each chunk ends with at least 1-3 `00`, which terminates the string earlier.

In this case, any attempt to specify buffer size (`col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1`) will fail because the trailing `00`s are all copied so that `out` is also terminated earlier.

The following is the output.

```
> d2 <- dbGetQuery(con, "select CONTENT from CMB_REPORT_RESEARCH where ID = 1067315")
nanodbc/nanodbc.cpp:693 SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &env)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:705 SQLSetEnvAttr(env, SQL_ATTR_ODBC_VERSION, (SQLPOINTER)NANODBC_ODBC_VERSION, SQL_IS_UINTEGER)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:724 SQLAllocHandle(SQL_HANDLE_DBC, env, &conn)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1275 SQLAllocHandle(SQL_HANDLE_STMT, conn.native_dbc_handle(), &stmt_)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:825 SQLFreeHandle(SQL_HANDLE_DBC, conn_)
nanodbc/nanodbc.cpp:826 SQLFreeHandle(SQL_HANDLE_ENV, env_)
nanodbc/nanodbc.cpp:1344 SQLPrepare(stmt_, (NANODBC_SQLCHAR*)query.c_str(), (SQLINTEGER)query.size())
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1362 SQLSetStmtAttr(stmt_, SQL_ATTR_QUERY_TIMEOUT, (SQLPOINTER)(std::intptr_t)timeout, 0)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1665 SQLNumParams(stmt_, &params)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1563 SQLFreeStmt(stmt_, SQL_CLOSE)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1581 SQLSetStmtAttr(stmt_, SQL_ATTR_PARAMSET_SIZE, (SQLPOINTER)(std::intptr_t)batch_operations, 0)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1362 SQLSetStmtAttr(stmt_, SQL_ATTR_QUERY_TIMEOUT, (SQLPOINTER)(std::intptr_t)timeout, 0)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1587 SQLExecute(stmt_)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2135 SQLSetStmtAttr(stmt_.native_statement_handle(), SQL_ATTR_ROW_ARRAY_SIZE, (SQLPOINTER)(std::intptr_t)rowset_size_, 0)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2145 SQLSetStmtAttr(stmt_.native_statement_handle(), SQL_ATTR_ROWS_FETCHED_PTR, &row_count_, 0)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1648 SQLNumResultCols(stmt_, &cols)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2566 SQLDescribeCol(stmt_.native_statement_handle(), i + 1, (NANODBC_SQLCHAR*)column_name, sizeof(column_name) / sizeof(NANODBC_SQLCHAR), &len, &sqltype, &sqlsize, &scale, &nullable)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2687 SQLBindCol(stmt_.native_statement_handle(), i + 1, col.ctype_, 0, 0, col.cbdata_)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:1648 SQLNumResultCols(stmt_, &cols)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2516 SQLFetchScroll(stmt_.native_statement_handle(), orientation, rows)
buffer_size: 256
buffer: 
ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 ffffffe6 ffffff8a ffffff95 ffffffe8 ffffffb5 ffffff84 ffffffe8 ffffffa6 ffffff81 ffffffe7 ffffff82 ffffffb9 ffffffef ffffffbc ffffff9a 0a 0a ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 32 30 31 37 ffffffe5 ffffffb9 ffffffb4 ffffffe6 ffffff8a ffffffa5 ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff85 ffffffa5 31 31 2e 36 ffffffe4 ffffffba ffffffbf ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffff8d ffffff87 34 39 2e 38 25 ffffffef ffffffbc ffffff8c ffffffe5 ffffffbd ffffff92 ffffffe6 ffffffaf ffffff8d ffffffe5 ffffff87 ffffff80 ffffffe5 ffffff88 ffffffa9 ffffffe6 ffffffb6 ffffffa6 31 2e 33 ffffffe4 ffffffba ffffffbf ffffffe5 ffffff85 ffffff83 ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffff8d ffffff87 35 38 2e 38 25 ffffffef ffffffbc ffffff8c 45 50 53 ffffffe4 ffffffb8 ffffffba 31 2e 31 ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe7 ffffffac ffffffa6 ffffffe5 ffffff90 ffffff88 ffffffe9 ffffffa2 ffffff84 ffffffe6 ffffff9c ffffff9f ffffffe3 ffffff80 ffffff82 31 ffffffef ffffffbc ffffff89 42 32 43 ffffffe4 ffffffb8 ffffff9a ffffffe5 ffffff8a ffffffa1 ffffffe5 ffffffae ffffff9e ffffffe7 ffffff8e ffffffb0 ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff85 ffffffa5 ffffffe8 ffffffb6 ffffff85 35 ffffffe4 ffffffba ffffffbf ffffffef ffffffbc ffffff8c ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf 31 32 30 25 ffffffef ffffffbc ffffff8c 42 32 42 ffffffe5 ffffffae ffffff9e ffffffe7 ffffff8e ffffffb0 ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff85 ffffffa5 36 2e 36 ffffffe4 ffffffba ffffffbf ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffff8d ffffff87 32 30 2e 32 25 ffffffef ffffffbc ffffff9b 32 00 00 
buffer_size: 256
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffef ffffffbc ffffff89 ffffffe6 ffffff8b ffffff9f ffffffe6 ffffffaf ffffff8f 31 30 ffffffe8 ffffff82 ffffffa1 ffffffe8 ffffffbd ffffffac ffffffe5 ffffffa2 ffffff9e 38 ffffffe8 ffffff82 ffffffa1 ffffffe6 ffffffb4 ffffffbe 33 2e 33 ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe5 ffffff88 ffffff86 ffffffe7 ffffffba ffffffa2 ffffffe6 ffffffaf ffffff94 ffffffe7 ffffff8e ffffff87 32 39 2e 39 25 ffffffe3 ffffff80 ffffff82 33 ffffffef ffffffbc ffffff89 31 38 ffffffe5 ffffffb9 ffffffb4 51 31 ffffffe6 ffffff89 ffffffa3 ffffffe9 ffffff9d ffffff9e ffffffe5 ffffff87 ffffff80 ffffffe5 ffffff88 ffffffa9 ffffffe7 ffffffac ffffffa6 ffffffe5 ffffff90 ffffff88 ffffffe9 ffffffa2 ffffff84 ffffffe6 ffffff9c ffffff9f ffffffef ffffffbc ffffff8c ffffffe9 ffffffa2 ffffff84 ffffffe8 ffffffae ffffffa1 31 38 ffffffe5 ffffffb9 ffffffb4 51 31 ffffffe5 ffffffad ffffffa3 ffffffe5 ffffffba ffffffa6 ffffffe5 ffffffae ffffff9e ffffffe7 ffffff8e ffffffb0 ffffffe5 ffffffbd ffffff92 ffffffe6 ffffffaf ffffff8d ffffffe5 ffffff87 ffffff80 ffffffe5 ffffff88 ffffffa9 ffffffe6 ffffffb6 ffffffa6 33 33 31 30 2d 33 35 38 30 ffffffe4 ffffffb8 ffffff87 ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf 32 30 2d 33 30 25 ffffffef ffffffbc ffffff8c ffffffe4 ffffffb8 ffffffbb ffffffe8 ffffffa6 ffffff81 ffffffe6 ffffff98 ffffffaf ffffffe5 ffffff8e ffffffbb ffffffe5 ffffffb9 ffffffb4 ffffffe5 ffffff90 ffffff8c ffffffe6 ffffff9c ffffff9f ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff88 ffffffb0 36 30 30 ffffffe4 ffffffb8 ffffff87 ffffffe5 ffffff85 ffffff83 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffffb8 ffffff82 ffffffe6 ffffff94 ffffffbf ffffffe5 ffffffba ffffff9c ffffffe8 ffffffa1 ffffffa5 ffffffe8 ffffffb4 ffffffb4 ffffffef ffffffbc ffffff8c ffffffe9 ffffffa2 ffffff84 ffffffe8 ffffffae ffffffa1 31 38 ffffffe5 ffffffb9 ffffffb4 ffffffe4 ffffffb8 ffffff80 ffffffe5 ffffffad ffffffa3 ffffffe5 ffffffba ffffffa6 ffffffe6 ffffff89 ffffffa3 00 00 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe9 ffffff9d ffffff9e ffffffe5 ffffff90 ffffff8e ffffffe5 ffffff90 ffffff8c ffffffe6 ffffffaf ffffff94 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf 34 33 25 2d 35 35 25 ffffffe3 ffffff80 ffffff82 0a 0a ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe7 ffffff9b ffffff88 ffffffe5 ffffff88 ffffffa9 ffffffe8 ffffff83 ffffffbd ffffffe5 ffffff8a ffffff9b ffffffe6 ffffff8c ffffff81 ffffffe7 ffffffbb ffffffad ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 ffffffef ffffffbc ffffff8c ffffffe8 ffffff87 ffffffaa ffffffe4 ffffffb8 ffffffbb ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe5 ffffff8f ffffff91 ffffffe5 ffffffb1 ffffff95 ffffffe6 ffffff95 ffffff85 ffffffe5 ffffffad ffffff98 ffffffe8 ffffffb4 ffffffa7 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffff8d ffffff87 ffffffe6 ffffff98 ffffff8e ffffffe6 ffffff98 ffffffbe ffffffef ffffffbc ffffff8c ffffffe8 ffffffb5 ffffff84 ffffffe4 ffffffba ffffffa7 ffffffe8 ffffffb4 ffffffa8 ffffffe9 ffffff87 ffffff8f ffffffe8 ffffffbe ffffff83 ffffffe7 ffffffa8 ffffffb3 ffffffe5 ffffff81 ffffffa5 ffffffe3 ffffff80 ffffff82 31 ffffffef ffffffbc ffffff89 ffffffe5 ffffffad ffffff98 ffffffe8 ffffffb4 ffffffa7 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf 31 35 38 25 ffffffe8 ffffff87 ffffffb3 32 2e 38 ffffffe4 ffffffba ffffffbf ffffffe5 ffffff85 ffffff83 ffffffef ffffffbc ffffff8c ffffffe4 ffffffb8 ffffffbb ffffffe8 ffffffa6 ffffff81 ffffffe6 ffffff98 ffffffaf ffffffe8 ffffff87 ffffffaa ffffffe4 ffffffb8 ffffffbb ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe8 ffffffbf ffffff9e ffffffe7 ffffffbb ffffffad ffffffe7 ffffffbf ffffffbb ffffffe7 ffffff95 ffffffaa ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf ffffffef ffffffbc ffffff8c 53 4b 55 ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe6 ffffff89 ffffffa9 ffffffe5 ffffff85 ffffff85 ffffffef ffffffbc ffffff8c ffffffe5 ffffffaf ffffffbc ffffffe8 ffffff87 ffffffb4 ffffffe5 ffffffae ffffff89 ffffffe5 ffffff85 ffffffa8 ffffffe5 ffffffa4 ffffff87 ffffffe8 ffffffb4 ffffffa7 00 00 
buffer_size: 256
buffer: 
ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf ffffffe3 ffffff80 ffffff82 32 ffffffef ffffffbc ffffff89 ffffffe4 ffffffb8 ffffff9a ffffffe5 ffffff8a ffffffa1 ffffffe7 ffffffbb ffffff93 ffffffe6 ffffff9e ffffff84 ffffffe4 ffffffbc ffffff98 ffffffe5 ffffff8c ffffff96 ffffffef ffffffbc ffffff8c ffffffe8 ffffffb4 ffffffb9 ffffffe7 ffffff94 ffffffa8 ffffffe7 ffffff8e ffffff87 ffffffe7 ffffffae ffffffa1 ffffffe6 ffffff8e ffffffa7 ffffffe8 ffffff89 ffffffaf ffffffe5 ffffffa5 ffffffbd ffffffef ffffffbc ffffff8c ffffffe7 ffffff9b ffffff88 ffffffe5 ffffff88 ffffffa9 ffffffe8 ffffff83 ffffffbd ffffffe5 ffffff8a ffffff9b ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 ffffffe3 ffffff80 ffffff82 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe4 ffffffbe ffffff9b ffffffe5 ffffffba ffffff94 ffffffe9 ffffff93 ffffffbe ffffffe6 ffffff8f ffffff90 ffffffe6 ffffff95 ffffff88 ffffffe5 ffffffb7 ffffffb2 ffffffe6 ffffff9c ffffff89 ffffffe6 ffffff89 ffffff80 ffffffe4 ffffffbd ffffff93 ffffffe7 ffffff8e ffffffb0 ffffffef ffffffbc ffffff8c ffffffe6 ffffffaf ffffff9b ffffffe5 ffffff88 ffffffa9 ffffffe7 ffffff8e ffffff87 ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 30 2e 38 70 63 74 ffffffe8 ffffff87 ffffffb3 32 39 2e 36 25 ffffffef ffffffbc ffffff8c ffffffe5 ffffffb8 ffffffa6 ffffffe5 ffffff8a ffffffa8 ffffffe5 ffffff87 ffffff80 ffffffe5 ffffff88 ffffffa9 ffffffe7 ffffff8e ffffff87 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffff8d ffffff87 31 2e 37 ffffffe4 ffffffb8 ffffffaa 70 63 74 ffffffe8 ffffff87 ffffffb3 31 32 2e 32 25 ffffffe3 ffffff80 ffffff82 ffffffe7 ffffff94 ffffffb1 ffffffe4 ffffffba ffffff8e ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe9 ffffff95 ffffffbf ffffffe4 ffffffba ffffff8e ffffffe4 ffffffbd ffffffbf ffffffe7 ffffff94 ffffffa8 ffffffe6 ffffff88 ffffff90 ffffffe6 ffffff9c ffffffac ffffffe8 ffffffbe ffffff83 ffffffe4 ffffffbd ffffff8e ffffffe7 ffffff9a ffffff84 ffffffe8 ffffff87 ffffffaa ffffffe5 ffffffaa ffffff92 ffffffe4 ffffffbd ffffff93 ffffffe6 ffffff8e ffffffa8 ffffffe5 ffffffb9 ffffffbf ffffffe6 ffffff96 ffffffb9 ffffffe5 ffffffbc ffffff8f ffffffef ffffffbc ffffff8c 42 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
32 43 ffffffe4 ffffffb8 ffffff9a ffffffe5 ffffff8a ffffffa1 ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe6 ffffff89 ffffffa9 ffffffe5 ffffffbc ffffffa0 ffffffef ffffffbc ffffff8c ffffffe9 ffffff94 ffffff80 ffffffe5 ffffff94 ffffffae ffffffe8 ffffffb4 ffffffb9 ffffffe7 ffffff94 ffffffa8 ffffffe7 ffffff8e ffffff87 ffffffe4 ffffffbb ffffff85 38 2e 34 25 ffffffef ffffffbc ffffff8c ffffffe5 ffffff9f ffffffba ffffffe6 ffffff9c ffffffac ffffffe6 ffffff8c ffffff81 ffffffe5 ffffffb9 ffffffb3 ffffffef ffffffbc ffffff9b ffffffe7 ffffffb2 ffffffbe ffffffe7 ffffff9b ffffff8a ffffffe7 ffffffae ffffffa1 ffffffe7 ffffff90 ffffff86 ffffffe8 ffffff87 ffffffb4 ffffffe6 ffffff95 ffffff88 ffffffe7 ffffff8e ffffff87 ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 ffffffef ffffffbc ffffff8c ffffffe7 ffffffae ffffffa1 ffffffe7 ffffff90 ffffff86 ffffffe8 ffffffb4 ffffffb9 ffffffe7 ffffff94 ffffffa8 ffffffe7 ffffff8e ffffff87 ffffffe9 ffffff99 ffffff8d ffffffe4 ffffffbd ffffff8e 31 2e 35 36 70 63 74 ffffffe8 ffffff87 ffffffb3 38 2e 30 25 ffffffef ffffffbc ffffff8c ffffffe6 ffffff96 ffffffb0 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffffa0 ffffff94 ffffffe5 ffffff8f ffffff91 ffffffe4 ffffffb8 ffffff8d ffffffe6 ffffff96 ffffffad ffffffe5 ffffff8a ffffffa0 ffffffe7 ffffffa0 ffffff81 ffffffef ffffffbc ffffff8c ffffffe7 ffffffa0 ffffff94 ffffffe5 ffffff8f ffffff91 ffffffe8 ffffffb4 ffffffb9 ffffffe7 ffffff94 ffffffa8 ffffffe7 ffffff8e ffffff87 33 25 ffffffe4 ffffffbf ffffff9d ffffffe6 ffffff8c ffffff81 ffffffe9 ffffffab ffffff98 ffffffe6 ffffffb0 ffffffb4 ffffffe5 ffffffb9 ffffffb3 ffffffe3 ffffff80 ffffff82 33 ffffffef ffffffbc ffffff89 ffffffe7 ffffff8e ffffffb0 ffffffe9 ffffff87 ffffff91 ffffffe6 ffffffb5 ffffff81 ffffffe5 ffffff81 ffffffa5 ffffffe5 ffffffba ffffffb7 ffffffef ffffffbc ffffff8c ffffffe7 ffffffbb ffffff8f ffffffe8 ffffff90 ffffffa5 ffffffe6 ffffff80 ffffffa7 ffffffe7 ffffff8e ffffffb0 ffffffe9 ffffff87 ffffff91 ffffffe6 ffffffb5 ffffff81 ffffffe5 ffffff87 ffffff80 ffffffe9 ffffffa2 ffffff9d ffffffe5 ffffffa4 ffffffa7 ffffffe5 ffffffb9 ffffff85 ffffffe5 ffffffa2 ffffff9e ffffffe5 ffffff8a ffffffa0 37 35 25 00 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe8 ffffff87 ffffffb3 31 2e 35 ffffffe4 ffffffba ffffffbf ffffffe5 ffffff85 ffffff83 ffffffe3 ffffff80 ffffff82 0a 0a ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 42 32 43 ffffffe8 ffffff87 ffffffaa ffffffe4 ffffffb8 ffffffbb ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff85 ffffffa5 ffffffe5 ffffff8d ffffffa0 ffffffe6 ffffffaf ffffff94 ffffffe8 ffffffb6 ffffff85 34 33 25 ffffffef ffffffbc ffffff8c ffffffe5 ffffffa4 ffffff9a ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff9c ffffffba ffffffe6 ffffff99 ffffffaf ffffffe5 ffffffb8 ffffff83 ffffffe5 ffffffb1 ffffff80 ffffffe8 ffffffbf ffffff9b ffffffe8 ffffffa1 ffffff8c ffffffe6 ffffff97 ffffffb6 ffffffef ffffffbc ffffff8c ffffffe5 ffffffb0 ffffff8f ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffff94 ffffff9f ffffffe6 ffffff80 ffffff81 ffffffe9 ffffff93 ffffffbe ffffffe6 ffffffb8 ffffffa0 ffffffe9 ffffff81 ffffff93 ffffffe7 ffffffba ffffffa2 ffffffe5 ffffff88 ffffffa9 ffffffe6 ffffff8c ffffff81 ffffffe7 ffffffbb ffffffad ffffffe9 ffffff87 ffffff8a ffffffe6 ffffff94 ffffffbe ffffffef ffffffbc ffffff8c ffffffe9 ffffffa2 ffffff84 ffffffe8 ffffffae ffffffa1 ffffffe7 ffffffbf ffffffbb ffffffe5 ffffff80 ffffff8d ffffffe9 ffffffab ffffff98 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf ffffffe5 ffffffb0 ffffff86 ffffffe6 ffffff8c ffffff81 ffffffe7 ffffffbb ffffffad ffffffe3 ffffff80 ffffff82 31 ffffffef ffffffbc ffffff89 ffffffe6 ffffffb6 ffffffa6 ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffff9b ffffff88 ffffffe5 ffffff88 ffffffa9 ffffffe8 ffffff83 ffffffbd ffffffe5 ffffff8a ffffff9b ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 ffffffef ffffffbc ffffff8c 39 30 ffffffe5 ffffff88 ffffff86 ffffffe6 ffffff88 ffffff90 ffffffe4 ffffffb8 ffffffba ffffffe6 ffffff9c ffffffac ffffffe5 ffffff9c ffffff9f ffffffe7 ffffffac ffffffac ffffffe4 ffffffb8 ffffff80 ffffffe7 ffffffae ffffffb1 ffffffe5 ffffff8c ffffff85 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffef ffffffbc ffffff8c ffffffe6 ffffffb3 ffffff9b ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff93 ffffff81 00 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe7 ffffff89 ffffff8c ffffffe6 ffffff82 ffffffa0 ffffffe5 ffffff90 ffffffaf ffffffe4 ffffffb9 ffffffb0 ffffffe6 ffffff89 ffffff8b ffffffe5 ffffff88 ffffffb6 ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe4 ffffffb8 ffffffb0 ffffffe5 ffffffaf ffffff8c 53 4b 55 ffffffe3 ffffff80 ffffff82 39 30 ffffffe5 ffffff88 ffffff86 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe7 ffffffb4 ffffffaf ffffffe8 ffffffae ffffffa1 ffffffe7 ffffffae ffffffb1 ffffffe5 ffffff8c ffffff85 ffffffe9 ffffff94 ffffff80 ffffffe9 ffffff87 ffffff8f ffffffe5 ffffffb7 ffffffb2 ffffffe7 ffffffa0 ffffffb4 32 30 30 ffffffe4 ffffffb8 ffffff87 ffffffe5 ffffff8f ffffffaa ffffffef ffffffbc ffffff8c ffffffe5 ffffff85 ffffffa8 ffffffe6 ffffffb8 ffffffa0 ffffffe9 ffffff81 ffffff93 ffffffe5 ffffffb8 ffffff83 ffffffe5 ffffffb1 ffffff80 ffffffe5 ffffff8a ffffffa0 ffffffe9 ffffff80 ffffff9f ffffffef ffffffbc ffffff8c ffffffe9 ffffffbb ffffff91 ffffffe7 ffffffa7 ffffff91 ffffffe6 ffffff8a ffffff80 ffffffe6 ffffff8f ffffff90 ffffffe5 ffffff8d ffffff87 ffffffe8 ffffffb0 ffffff83 ffffffe6 ffffff80 ffffffa7 ffffffef ffffffbc ffffff8c ffffffe8 ffffff80 ffffff81 ffffffe5 ffffff93 ffffff81 ffffffe8 ffffffbf ffffffad ffffffe4 ffffffbb ffffffa3 2b ffffffe6 ffffff96 ffffffb0 ffffffe5 ffffff93 ffffff81 ffffffe6 ffffff8e ffffffa8 ffffffe5 ffffff87 ffffffba ffffffe5 ffffffa4 ffffff9a ffffffe8 ffffffbd ffffffae ffffffe9 ffffffa9 ffffffb1 ffffffe5 ffffff8a ffffffa8 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe5 ffffff8f ffffff91 ffffffe5 ffffffb1 ffffff95 ffffffe3 ffffff80 ffffff82 32 ffffffef ffffffbc ffffff89 ffffffe7 ffffffa1 ffffff95 ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffffa8 ffffff9a ffffffe8 ffffffa1 ffffff8c ffffffe6 ffffff8a ffffff8a ffffffe6 ffffff8f ffffffa1 ffffffe5 ffffffa9 ffffffb4 ffffffe7 ffffffab ffffffa5 ffffffe9 ffffffa3 ffffff8e ffffffe5 ffffff8f ffffffa3 ffffffef ffffffbc ffffff8c ffffffe4 ffffffbb ffffff8e 30 ffffffe5 ffffff88 ffffffb0 31 ffffffe5 ffffffbe ffffff85 ffffffe7 ffffffa0 ffffffb4 ffffffe5 ffffffa3 ffffffb3 ffffffef ffffffbc ffffff8c ffffffe6 ffffff9c ffffff89 ffffffe6 ffffff9c ffffff9b ffffffe5 ffffffa4 ffffff8d ffffffe5 ffffff88 ffffffb6 ffffffe6 ffffffb6 ffffffa6 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe7 ffffffb1 ffffffb3 ffffffe6 ffffff88 ffffff90 ffffffe5 ffffff8a ffffff9f ffffffe3 ffffff80 ffffff82 ffffffe2 ffffff80 ffffff9c ffffffe5 ffffffb0 ffffff8f ffffffe8 ffffffbd ffffffbb ffffffe6 ffffff98 ffffff9f ffffffe2 ffffff80 ffffff9d ffffffe5 ffffff84 ffffffbf ffffffe7 ffffffab ffffffa5 ffffffe6 ffffff8e ffffffa8 ffffffe8 ffffffbd ffffffa6 ffffffe5 ffffffbb ffffffb6 ffffffe7 ffffffbb ffffffad 39 30 ffffffe5 ffffff88 ffffff86 ffffffe9 ffffffab ffffff98 ffffffe6 ffffff80 ffffffa7 ffffffe4 ffffffbb ffffffb7 ffffffe6 ffffffaf ffffff94 ffffffe7 ffffff9a ffffff84 ffffffe7 ffffff89 ffffffb9 ffffffe8 ffffffb4 ffffffa8 ffffffe5 ffffffb7 ffffffb2 ffffffe5 ffffff9c ffffffa8 ffffffe7 ffffffb1 ffffffb3 ffffffe5 ffffffae ffffffb6 ffffffe6 ffffff9c ffffff89 ffffffe5 ffffff93 ffffff81 ffffffe6 ffffff8a ffffff95 ffffffe6 ffffff94 ffffffbe ffffffef ffffffbc ffffff8c ffffffe5 ffffffb0 ffffff8f ffffffe8 ffffff8c ffffff83 ffffffe5 ffffff9b ffffffb4 ffffffe8 ffffffaf ffffff95 ffffffe6 ffffffb0 ffffffb4 ffffffe5 ffffff90 ffffff8e ffffffe4 ffffffbe ffffff9d ffffffe6 ffffff89 ffffff98 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe8 ffffffbf ffffffad ffffffe4 ffffffbb ffffffa3 ffffffe8 ffffff83 ffffffbd ffffffe5 ffffff8a ffffff9b ffffffef ffffffbc ffffff8c ffffffe6 ffffff9c ffffff89 ffffffe6 ffffff9c ffffff9b ffffffe5 ffffff9c ffffffa8 ffffffe5 ffffffa9 ffffffb4 ffffffe7 ffffffab ffffffa5 ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe9 ffffffa2 ffffff86 ffffffe5 ffffff9f ffffff9f ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe5 ffffff88 ffffff87 ffffffe5 ffffff85 ffffffa5 ffffffe5 ffffffb8 ffffff82 ffffffe5 ffffff9c ffffffba ffffffe5 ffffffa4 ffffff8d ffffffe5 ffffff88 ffffffb6 ffffffe6 ffffffb6 ffffffa6 ffffffe7 ffffffb1 ffffffb3 ffffffe6 ffffff88 ffffff90 ffffffe5 ffffff8a ffffff9f ffffffe3 ffffff80 ffffff82 33 ffffffef ffffffbc ffffff89 ffffffe6 ffffffb6 ffffffa6 ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffffa1 ffffff95 ffffffe7 ffffffb1 ffffffb3 ffffffe4 ffffffb8 ffffffa4 ffffffe5 ffffffae ffffffb6 ffffffe5 ffffffb0 ffffff8f ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffff94 ffffff9f ffffffe6 ffffff80 ffffff81 ffffffe9 ffffff93 ffffffbe ffffffe5 ffffffad ffffff90 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe6 ffffff8c ffffff81 ffffffe8 ffffff82 ffffffa1 ffffffe5 ffffffa2 ffffff9e ffffffe8 ffffff87 ffffffb3 37 36 25 ffffffe5 ffffffae ffffff8c ffffffe6 ffffff88 ffffff90 ffffffef ffffffbc ffffff8c ffffffe5 ffffffbd ffffffb0 ffffffe6 ffffff98 ffffffbe ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe4 ffffffbf ffffffa1 ffffffe5 ffffffbf ffffff83 ffffffe3 ffffff80 ffffff82 0a 0a ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 42 32 42 ffffffe7 ffffffab ffffffaf ffffffe7 ffffffb2 ffffffbe ffffffe7 ffffff9b ffffff8a ffffffe5 ffffff88 ffffffb6 ffffffe9 ffffff80 ffffffa0 ffffffe5 ffffff8d ffffff87 ffffffe7 ffffffba ffffffa7 2b ffffffe6 ffffff8c ffffff96 ffffffe6 ffffff8e ffffff98 ffffffe6 ffffff96 ffffffb0 ffffffe9 ffffff9b ffffffb6 ffffffe5 ffffff94 ffffffae ffffffe5 ffffffae ffffffa2 ffffffe6 ffffff88 ffffffb7 ffffffef ffffffbc ffffff8c ffffffe9 ffffffa2 ffffff84 ffffffe8 ffffffae ffffffa1 ffffffe6 ffffff9c ffffffaa ffffffe6 ffffff9d ffffffa5 ffffffe4 ffffffbb ffffff8d ffffffe8 ffffff83 ffffffbd ffffffe7 ffffffbb ffffffb4 ffffffe6 ffffff8c ffffff81 32 30 25 2b ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf ffffffe3 ffffff80 ffffff82 31 ffffffef ffffffbc ffffff89 ffffffe5 ffffff8e ffffff9f ffffffe6 ffffff9c ffffff89 ffffffe4 ffffffbc ffffff98 ffffffe8 ffffffb4 ffffffa8 ffffffe5 ffffffae ffffffa2 ffffffe6 ffffff88 ffffffb7 ffffffe5 ffffff90 ffffff88 ffffffe4 ffffffbd ffffff9c ffffffe5 ffffff85 ffffffb3 ffffffe7 ffffffb3 ffffffbb ffffffe7 ffffffa8 ffffffb3 ffffffe5 ffffffae ffffff9a ffffffe3 ffffff80 ffffff82 ffffffe6 ffffff88 ffffff90 ffffffe4 ffffffb8 ffffffba ffffffe8 ffffffbf ffffffaa ffffffe5 ffffff8d ffffffa1 ffffffe4 ffffffbe ffffffac ffffffe6 ffffff88 ffffff98 ffffffe7 ffffff95 ffffffa5 ffffffe5 ffffff90 ffffff88 ffffffe4 ffffffbd ffffff9c ffffffe4 ffffffbc ffffff99 ffffffe4 ffffffbc ffffffb4 ffffffef ffffffbc ffffff8c ffffffe8 ffffffbf ffffff9b ffffffe4 ffffffb8 ffffff80 ffffffe6 ffffffad ffffffa5 ffffffe6 ffffff8c ffffff96 ffffffe6 ffffff8e ffffff98 ffffffe4 ffffffb8 ffffff8e ffffffe8 ffffffbf ffffffaa ffffffe5 ffffff8d ffffffa1 00 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe4 ffffffbe ffffffac ffffffe3 ffffff80 ffffff81 ffffffe6 ffffff83 ffffffa0 ffffffe6 ffffff99 ffffffae ffffffe3 ffffff80 ffffff81 ffffffe8 ffffff81 ffffff94 ffffffe6 ffffff83 ffffffb3 ffffffe3 ffffff80 ffffff81 ffffffe6 ffffff96 ffffffb0 ffffffe7 ffffffa7 ffffff80 ffffffe4 ffffffb8 ffffffbd ffffffe7 ffffffad ffffff89 ffffffe5 ffffff9b ffffffbd ffffffe9 ffffff99 ffffff85 ffffffe7 ffffff9f ffffffa5 ffffffe5 ffffff90 ffffff8d ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe5 ffffff90 ffffff88 ffffffe4 ffffffbd ffffff9c ffffffe7 ffffff9a ffffff84 ffffffe6 ffffffb7 ffffffb1 ffffffe5 ffffffba ffffffa6 ffffffe5 ffffff92 ffffff8c ffffffe5 ffffffb9 ffffffbf ffffffe5 ffffffba ffffffa6 ffffffe3 ffffff80 ffffff82 32 ffffffef ffffffbc ffffff89 ffffffe6 ffffff96 ffffffb0 ffffffe5 ffffffa2 ffffff9e ffffffe5 ffffff90 ffffff8d ffffffe5 ffffff88 ffffff9b ffffffe4 ffffffbc ffffff98 ffffffe5 ffffff93 ffffff81 ffffffe5 ffffff92 ffffff8c ffffffe7 ffffffbd ffffff91 ffffffe6 ffffff98 ffffff93 ffffffe4 ffffffb8 ffffffa5 ffffffe9 ffffff80 ffffff89 ffffffe7 ffffffad ffffff89 ffffffe6 ffffff96 ffffffb0 ffffffe9 ffffff9b ffffffb6 ffffffe5 ffffff94 ffffffae ffffffe5 ffffffae ffffffa2 ffffffe6 ffffff88 ffffffb7 ffffffe7 ffffffb4 ffffffa7 ffffffe8 ffffffb7 ffffff9f ffffffe9 ffffffa3 ffffff8e ffffffe5 ffffff8f ffffffa3 ffffffe3 ffffff80 ffffff82 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe4 ffffffb8 ffffff8e ffffffe7 ffffffbd ffffff91 ffffffe6 ffffff98 ffffff93 ffffffe4 ffffffb8 ffffffa5 ffffffe9 ffffff80 ffffff89 ffffffe3 ffffff80 ffffff81 ffffffe6 ffffffb7 ffffff98 ffffffe5 ffffffae ffffff9d ffffffe5 ffffffbf ffffff83 ffffffe9 ffffff80 ffffff89 ffffffe7 ffffffad ffffff89 ffffffe6 ffffff96 ffffffb0 ffffffe9 ffffff9b ffffffb6 ffffffe5 ffffff94 ffffffae ffffffe5 ffffffae ffffffa2 ffffffe6 ffffff88 ffffffb7 ffffffe5 ffffff90 ffffff88 ffffffe4 ffffffbd ffffff9c ffffffe4 ffffffbb ffffff8d ffffffe5 ffffff9c ffffffa8 ffffffe6 ffffff8e ffffffa8 ffffffe8 ffffffbf ffffff9b ffffffef ffffffbc ffffff8c ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe4 ffffffb8 ffffff8e ffffffe5 ffffff90 ffffff8d ffffffe5 ffffff88 ffffff9b ffffffe4 ffffffbc ffffff98 ffffffe5 ffffff93 ffffff81 ffffffe6 ffffff88 ffffff90 ffffffe7 ffffffab ffffff8b 00 00 00 
buffer_size: 256
buffer: 
ffffffe5 ffffff90 ffffff88 ffffffe8 ffffffb5 ffffff84 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe5 ffffffb7 ffffffb2 ffffffe8 ffffff90 ffffffbd ffffffe5 ffffff9c ffffffb0 ffffffef ffffffbc ffffff8c ffffffe9 ffffffa2 ffffff84 ffffffe8 ffffffae ffffffa1 31 38 ffffffe5 ffffffb9 ffffffb4 ffffffe6 ffffff94 ffffffbe ffffffe9 ffffff87 ffffff8f ffffffef ffffffbc ffffff8c ffffffe6 ffffff9c ffffff89 ffffffe6 ffffff9c ffffff9b ffffffe5 ffffffb8 ffffffa6 ffffffe6 ffffff9d ffffffa5 ffffffe8 ffffffbf ffffff87 ffffffe4 ffffffba ffffffbf ffffffe6 ffffff94 ffffffb6 ffffffe5 ffffff85 ffffffa5 ffffffe3 ffffff80 ffffff82 33 ffffffef ffffffbc ffffff89 ffffffe5 ffffff85 ffffffa8 ffffffe7 ffffff90 ffffff83 ffffffe5 ffffff8c ffffff96 ffffffe5 ffffffb8 ffffff83 ffffffe5 ffffffb1 ffffff80 ffffffe6 ffffff8e ffffffa8 ffffffe8 ffffffbf ffffff9b ffffffef ffffffbc ffffff8c ffffffe5 ffffff8d ffffffb0 ffffffe5 ffffffba ffffffa6 ffffffe5 ffffffb7 ffffffa5 ffffffe5 ffffff8e ffffff82 ffffffe5 ffffffbb ffffffba ffffffe6 ffffff88 ffffff90 ffffffe3 ffffff80 ffffff82 0a 0a ffffffe3 ffffff80 ffffff80 ffffffe3 ffffff80 ffffff80 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe6 ffffff98 ffffffaf 41 ffffffe8 ffffff82 ffffffa1 ffffffe5 ffffffb0 ffffff8f ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffff94 ffffff9f ffffffe6 ffffff80 ffffff81 ffffffe5 ffffff9c ffffff88 ffffffe5 ffffff94 ffffffaf ffffffe4 ffffffb8 ffffff80 ffffffe4 ffffffb8 ffffff8a ffffffe5 ffffffb8 ffffff82 ffffffe6 ffffffa0 ffffff87 ffffffe7 ffffff9a ffffff84 ffffffef ffffffbc ffffff8c ffffffe6 ffffff8e ffffffa7 ffffffe8 ffffff82 ffffffa1 ffffffe4 ffffffb8 ffffffa4 ffffffe5 ffffffae ffffffb6 ffffffe5 ffffffb0 ffffff8f ffffffe7 ffffffb1 ffffffb3 ffffffe7 ffffff94 ffffff9f ffffffe6 ffffff80 ffffff81 ffffffe9 ffffff93 ffffffbe ffffffe4 ffffffbc ffffff81 ffffffe4 ffffffb8 ffffff9a ffffffe9 ffffffbd ffffff90 ffffffe5 ffffff8f ffffff91 ffffffe5 ffffff8a ffffff9b ffffffef ffffffbc ffffff8c ffffffe5 ffffff9b ffffffb4 ffffffe7 ffffffbb ffffff95 ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe6 ffffff89 ffffffa9 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffffb1 ffffffbb ffffffef ffffffbc ffffff8c ffffffe7 ffffffbb ffffffb4 00 
buffer_size: 256
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
buffer: 
ffffffe6 ffffff8c ffffff81 ffffffe5 ffffffa2 ffffff9e ffffffe6 ffffff8c ffffff81 ffffffe8 ffffffaf ffffff84 ffffffe7 ffffffba ffffffa7 ffffffe3 ffffff80 ffffff82 31 37 ffffffe5 ffffffb9 ffffffb4 ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 42 32 42 2b 42 32 43 ffffffe4 ffffffb8 ffffff9a ffffffe5 ffffff8a ffffffa1 ffffffe5 ffffff9d ffffff87 ffffffe5 ffffffae ffffff9e ffffffe7 ffffff8e ffffffb0 ffffffe9 ffffffab ffffff98 ffffffe5 ffffffa2 ffffff9e ffffffe9 ffffff95 ffffffbf ffffffe3 ffffff80 ffffff82 ffffffe7 ffffffa1 ffffff95 ffffffe7 ffffffb1 ffffffb3 ffffffe5 ffffffae ffffff9a ffffffe4 ffffffbd ffffff8d ffffffe5 ffffffae ffffff8c ffffffe6 ffffff88 ffffff90 ffffffef ffffffbc ffffff8c ffffffe7 ffffff9e ffffff84 ffffffe5 ffffff87 ffffff86 ffffffe5 ffffff84 ffffffbf ffffffe7 ffffffab ffffffa5 ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff9c ffffffba ffffffe6 ffffff99 ffffffaf ffffffef ffffffbc ffffff8c ffffffe6 ffffff9c ffffff89 ffffffe6 ffffff9c ffffff9b ffffffe5 ffffffa4 ffffff8d ffffffe5 ffffff88 ffffffb6 39 30 ffffffe5 ffffff88 ffffff86 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe6 ffffff88 ffffff90 ffffffe5 ffffff8a ffffff9f ffffffef ffffffbc ffffff8c ffffffe6 ffffffb3 ffffff9b ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffff8c ffffffe6 ffffff82 ffffffa0 ffffffe5 ffffff90 ffffffaf ffffffe5 ffffff8f ffffff91 ffffffe6 ffffff8c ffffffa5 ffffffe4 ffffffb9 ffffffb0 ffffffe6 ffffff89 ffffff8b ffffffe9 ffffff80 ffffff89 ffffffe5 ffffff93 ffffff81 ffffffe7 ffffff89 ffffffb9 ffffffe9 ffffff95 ffffffbf ffffffef ffffffbc ffffff8c ffffffe8 ffffffbf ffffff85 ffffffe9 ffffff80 ffffff9f ffffffe6 ffffff89 ffffffa9 ffffffe5 ffffff85 ffffff85 53 4b 55 ffffffe5 ffffffae ffffff9e ffffffe7 ffffff8e ffffffb0 ffffffe5 ffffff87 ffffffba ffffffe8 ffffffa1 ffffff8c ffffffe5 ffffff9c ffffffba ffffffe6 ffffff99 ffffffaf ffffffe6 ffffffb6 ffffff88 ffffffe8 ffffffb4 ffffffb9 ffffffe5 ffffff85 ffffffa8 ffffffe8 ffffffa6 ffffff86 ffffffe7 ffffff9b ffffff96 ffffffef ffffffbc ffffff8c ffffffe5 ffffff85 ffffffac ffffffe5 ffffff8f ffffffb8 ffffffe5 ffffff8d ffffffb3 ffffffe5 ffffffb0 ffffff86 00 00 
buffer_size: 256
buffer: 
ffffffe8 ffffffbf ffffff9b ffffffe5 ffffff85 ffffffa5 ffffffe6 ffffff96 ffffffb0 ffffffe5 ffffff93 ffffff81 ffffffe5 ffffffbf ffffffab ffffffe9 ffffff80 ffffff9f ffffffe5 ffffff8f ffffff91 ffffffe5 ffffffb8 ffffff83 ffffffe6 ffffff9c ffffff9f ffffffef ffffffbc ffffff8c ffffffe6 ffffff88 ffffff91 ffffffe4 ffffffbb ffffffac ffffffe7 ffffffbb ffffffb4 ffffffe6 ffffff8c ffffff81 ffffffe7 ffffff9b ffffff88 ffffffe5 ffffff88 ffffffa9 ffffffe9 ffffffa2 ffffff84 ffffffe6 ffffffb5 ffffff8b ffffffef ffffffbc ffffff8c 31 38 2d 32 30 ffffffe5 ffffffb9 ffffffb4 ffffffe5 ffffffbd ffffff92 ffffffe6 ffffffaf ffffff8d ffffffe5 ffffff87 ffffff80 ffffffe5 ffffff88 ffffffa9 ffffffe6 ffffffb6 ffffffa6 ffffffe5 ffffff88 ffffff86 ffffffe5 ffffff88 ffffffab ffffffe4 ffffffb8 ffffffba 32 2e 30 2f 32 2e 37 2f 33 2e 36 ffffffe4 ffffffba ffffffbf ffffffef ffffffbc ffffff8c ffffffe5 ffffffaf ffffffb9 ffffffe5 ffffffba ffffff94 50 45 ffffffe5 ffffff88 ffffff86 ffffffe5 ffffff88 ffffffab ffffffe4 ffffffb8 ffffffba 34 31 2f 33 31 2f 32 33 ffffffe5 ffffff80 ffffff8d ffffffef ffffffbc ffffff8c ffffffe7 ffffffbb ffffffb4 ffffffe6 ffffff8c ffffff81 ffffffe5 ffffffa2 ffffff9e ffffffe6 ffffff8c ffffff81 ffffffe8 ffffffaf ffffff84 ffffffe7 ffffffba ffffffa7 ffffffe3 ffffff80 ffffff82 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
nanodbc/nanodbc.cpp:2822 SQLGetData(handle, column + 1, col.ctype_, buffer, buffer_size, &ValueLenOrInd)
nanodbc/nanodbc.cpp:2516 SQLFetchScroll(stmt_.native_statement_handle(), orientation, rows)
nanodbc/nanodbc.cpp:1265 SQLCancel(stmt_)
nanodbc/nanodbc.cpp:1654 SQLFreeStmt(stmt_, SQL_RESET_PARAMS)
nanodbc/nanodbc.cpp:1267 SQLFreeHandle(SQL_HANDLE_STMT, stmt_)
```

## Expected  behavior

All the trailing zeros in `buffer` should be ignored as being appended to `out` so that it is not terminated by a chunk of buffer.

## Minimal Working Example

Use `strlen(buffer)` to determine length of string to append to `out` each time as suggested in https://github.com/r-dbi/odbc/pull/190.

### LINKED ISSUE #175: Infinite loop fetching text into buffer
## Environment

* nanodbc version:
* DBMS name/version: SQL Server
* ODBC connection string:
* OS and Compiler: Ubuntu 18.04, g++
* CMake settings:

## Actual behavior

This issue is from https://github.com/r-dbi/odbc/issues/171. Querying specific rows from my table will end up in hanging forever. It turns out that the while loop condition at https://github.com/nanodbc/nanodbc/blob/0f230abfc08e1a6ebe2a5319ebd93129202bb131/nanodbc/nanodbc.cpp#L2939 never violates but each time the buffer is all zeros.

## Expected  behavior

When buffer is filled with all zeros, the while loop should also terminate to avoid some rare case where it never ends.

## Minimal Working Example

In #174, the suggested solution computes `strlen(buffer)` in case of non-`SQL_C_BINARY`. On top of that, if it is zero, then break the loop, as suggested in https://github.com/r-dbi/odbc/pull/190/files#diff-0b9b3e04c00a1b1a48f9188466e2719bR2825.

### PR DESCRIPTION
**Pull request by renkun-ken**
## What does this PR do?

Fix text truncation caused by multiple trailing zeros in buffer (#174) and possible infinite looping when fetching text into buffer (#175).

## What are related issues/pull requests?

Closes #174.
Closes #175.

## Tasklist

 - [x] ~Add test case(s)~ Comment on rationale for the fix (see discussion below)
 - [x] Review
 - [x] Adjust for comments
 - [x] All CI builds and checks have passed

### CODE REVIEW

File: nanodbc/nanodbc.cpp [hunk 1]
```diff
@@ -2924,14 +2924,18 @@ inline void result::result_impl::get_ref_impl(short column, T& result) const
...
                     &ValueLenOrInd); // StrLen_or_IndPtr
-                if (ValueLenOrInd == SQL_NO_TOTAL)
-                    out.append(buffer, col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1);
-                else if (ValueLenOrInd > 0)
-                    out.append(
-                        buffer,
-                        std::min<std::size_t>(
-                            ValueLenOrInd,
-                            col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1));
+                if (ValueLenOrInd == SQL_NO_TOTAL || ValueLenOrInd > 0) {
```
Comment (mloskot) [inline nanodbc/nanodbc.cpp]: Your patch changes coding style/formatting, See the first Travis CI build job. You may need to run `clang-format` - `.clang-format` is provided in the tree.

File: nanodbc/nanodbc.cpp [hunk 2]
```diff
@@ -2924,14 +2924,18 @@ inline void result::result_impl::get_ref_impl(short column, T& result) const
...
+                    std::size_t append_size = col.ctype_ == SQL_C_BINARY ? buffer_size : strlen(buffer);
+                    if (append_size == 0) {
```
Comment (mloskot) [inline nanodbc/nanodbc.cpp]: A comment would be good to explain when this `append_size` may become Zero.
A test case would be even better - in fact, nanodbc does not not accept PRs without even a trivially minimal test case accompanying a fix.

I have no time to test it myself, but perhaps retrieving data like this would reproduce your problem you are trying to solve here:

```sql
SELECT CAST('A' + CHAR(0) + 'B' + CHAR(0) + 'C' + CHAR(0) + CHAR(0) AS varchar(max)) AS v
```

File: nanodbc/nanodbc.cpp (hunk 1 above)
Comment (renkun-ken) [reply nanodbc/nanodbc.cpp]: Sorry for the formatting change. I use VSCode and disables my local `formatOnSave`. Thanks for noticing `.clang-format` file. I'll configure my extension to respect this file.

File: nanodbc/nanodbc.cpp (hunk 2 above)
Comment (renkun-ken) [reply nanodbc/nanodbc.cpp]: Thanks for your kind reminding! I'll modify this accordingly and add test cases in a while.

File: nanodbc/nanodbc.cpp [hunk 3]
```diff
@@ -2924,14 +2924,27 @@ inline void result::result_impl::get_ref_impl(short column, T& result) const
...
-                else if (ValueLenOrInd > 0)
-                    out.append(
-                        buffer,
-                        std::min<std::size_t>(
-                            ValueLenOrInd,
-                            col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1));
+                if (ValueLenOrInd == SQL_NO_TOTAL || ValueLenOrInd > 0)
+                {
+                    std::size_t append_size =
+                        col.ctype_ == SQL_C_BINARY ? buffer_size : strlen(buffer);
```
Comment (mloskot) [inline nanodbc/nanodbc.cpp]: `strlen` -> `std::strlen` for more C++ pedantic compilers

File: nanodbc/nanodbc.cpp (hunk 2 above)
Comment (renkun-ken) [reply nanodbc/nanodbc.cpp]: It's a little bit tricky to construct a case to determine how should interrupting zeros in text are "correctly handled" since `buffer_size` determines how the text is chunked. In each chunk, the interrupting zeros are present at different positions, making all subsequent chars after the first zero in the buffer ignored. When `buffer_size` is changed, the zero positions in each chunk are changed, so are the resulted strings appended to the result.

**Comment by renkun-ken** [comment]
It's a little bit tricky to construct a case to show how interrupting zeros in text should be handled since `buffer_size` determines how the text is chunked. In each chunk, the interrupting zeros are present at different positions, making all subsequent chars after the first zero in the buffer ignored. When `buffer_size` is changed, the zero positions in each chunk are changed, so are the resulted strings appended to the result.

**Comment by mloskot** [comment]
@renkun-ken 
> It's a little bit tricky to construct a case 

It may be indeed, I think.
The comment should be enough to explain the rationale for the fix.

**Comment by renkun-ken** [comment]
The test case I added is subject to the choice of `buffer_size` (currently 1024). If it is changed, then this test case will sadly break.

File: test/mssql_test.cpp [hunk 4]
```diff
@@ -468,6 +468,59 @@ TEST_CASE_METHOD(mssql_fixture, "test_string_with_varchar_max", "[mssql][string]
...
+        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
+        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
+        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
+
+    // 32 C
+    nanodbc::string chunk3 = NANODBC_TEXT("CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC");
+    nanodbc::result results = execute(
+        connection,
+        NANODBC_TEXT(
+            "select cast('" + chunk1 + "' + CHAR(0) + '" + chunk2 +
```
Comment (mloskot) [inline test/mssql_test.cpp]: https://ci.appveyor.com/project/nanodbc/nanodbc/build/1.0.122 
Compilation of this is failing with Unicode enabled because `NANODBC_TEXT` must be applied to each individual literal:
 ```
NANODBC_TEXT("select cast('") + chunk1 + NANODBC_TEXT("' + CHAR(0) + '") + chunk2 + ...
```

**Comment by mloskot** [comment]
@renkun-ken Thanks for the effort to add the test case!

**Comment by renkun-ken** [comment]
Thanks for your timely responds!

**Comment by mloskot** [comment]
@freddy77 Thanks for the comment
